---
abstract: 'Serialize tables to Excel files'
author:
  - 'Rafael Kitover <rkitover@cpan.org>'
build_requires:
  Spreadsheet::ParseExcel: 0
  Test::Deep: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Action-Serialize-SimpleExcel
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Controller::REST: 0
  Scalar::Util: 0
  Spreadsheet::WriteExcel: 0
  namespace::clean: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.011
